<a href="https://colab.research.google.com/github/hanzalaakeel/NIAI_Cohort_2026/blob/main/NETSOL_AI_ML_Tasks/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



## Introduction

We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We don't expect prior experience with Python and `numpy` but do expect some prior programming; the next section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing. Individuals with prior experience are advised to follow through for quick revision of concepts but may skip to the tasks if they wish to do so. Please make sure to run <span style="color: red;"> all cells </span> regardless.

Some of the things to be covered:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes

* `numpy`: Arrays, Array indexing, Datatypes, Array math, Broadcasting

* `matplotlib`: Plotting, Subplots, Images

* `scipy`: Images

* `pandas` : Reading and analyzing data



## Basics of Python



### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"

<class 'int'>
3


In [ ]:
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"

4
2
6
9


In [ ]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [ ]:
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment, or decrement operators, i.e. `x++` and `x--` respectively.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words (`and`, `or`) rather than symbols (`&&`, `||`, etc.):

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


#### Strings

Python has great support for strings:

In [ ]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

### Containers

Python includes several built-in container types: lists (`list`), dictionaries (`dict`), sets (`set`), and tuples (`tuple`).

#### Lists

A `list` is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

##### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing.

In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


##### List Comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [1]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [2]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [3]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [4]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#dict).

##### Loops

It is easy to iterate over the keys in a `dict`:

In [5]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


##### Dictionary Comprehensions

These are similar to list comprehensions, but allow you to easily construct `dict`s. For example:

In [6]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


#### Sets

A `set` is an unordered collection of distinct elements. As a simple example, consider the following:

In [7]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


As usual, everything you want to know about sets can be found in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#set).

##### Loops

Iterating over a `set` has the same syntax as iterating over a `list`; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [8]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: cat", "#3: dog"

#1: dog
#2: cat
#3: fish


##### Set Comprehensions

Like lists and dicts, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


The [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#tuples-and-sequences) has more information about tuples.

### Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


There is a lot more information about Python functions in the [documentation](https://docs.python.org/3.7/tutorial/controlflow.html#defining-functions).

#### Lambda Functions
These are anonymous functions in Python which take any number of arguments but only one expression. Their syntax generally follows:

`lambda arguments : expression`.

They are one line function and expression are representing the body of a normal function.

In [ ]:
l = lambda a : a+5  ## lambda function 'l' is created which is taking 'a' as an argument and expression adds 5 to the value of argument a
print(l(2))  ## passing 2 as value of 'a' argument of lambda function 'l' . This will return 7(7 = 2+5) as output.

l1 = lambda a,b,c : a * b * c ## lambda function 'l1' is created which is taking 3 arguments (a,b,c) and return the result by multiplying them all.
print(l1(10,20,30))  ## passing 10,20,30 as arguments 'a', 'b', 'c' respectively to 'l1' function. Print result 6000 (6000 = 10*20*30)

7
6000


### Classes

The syntax for defining classes in Python is straightforward:

In [9]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


# Tasks

### Q1
Write code to determine whether a number is even or odd and print it.

In [10]:
number = 5
if number % 2 == 0:
  print ("Even")
else:
  print ("Odd")

Odd


### Q2

For a given list of strings, check if the length of each string is even or odd. Print `even` or `odd` accordingly.

In [11]:
x = ['alphabets', 'numerics', 'data types', '123', 'wild', 'abc', 'chars']

for word in x:
    if len(word) % 2 == 0:
        print(f"{word} -> Even")
    else:
        print(f"{word} -> Odd")

alphabets -> Odd
numerics -> Even
data types -> Even
123 -> Odd
wild -> Even
abc -> Odd
chars -> Odd


### Q3

Write a code to reverse the string `hello` using indexing and print it.

In [12]:
greeting='hello'

print(greeting[::-1])

olleh


### Q4

For numbers in range `0` to `100`, return a list of those that are multiple of `2` but not `5`

In [13]:
def get_numbers():
    return [num for num in range(0, 101)
            if num % 2 == 0 and num % 5 != 0]

result = get_numbers()
print(result)

[2, 4, 6, 8, 12, 14, 16, 18, 22, 24, 26, 28, 32, 34, 36, 38, 42, 44, 46, 48, 52, 54, 56, 58, 62, 64, 66, 68, 72, 74, 76, 78, 82, 84, 86, 88, 92, 94, 96, 98]


### Q5

Write a Python function that accepts a string and calculates the number of upper case letters and lower case letters.

In [15]:
input_string = "Hello Mr. Rogers, how are you this fine Tuesday?"

def enum_cases(string):
    upper_count = 0
    lower_count = 0
    for char in string:
        if char.isupper():
            upper_count += 1
        elif char.islower():
            lower_count += 1
    return upper_count, lower_count

print('Upper case characters: %d\nLower case characters: %d'% enum_cases(input_string))

Upper case characters: 4
Lower case characters: 33


### Q6

Write a function that prints the integers from 1 to 100. But for multiples of three, print `Fizz` instead of the number, and for the multiples of five print `Buzz`. For numbers which are multiples of both three and five print `FizzBuzz`.

In [16]:
def special_print():
    for i in range(1, 101):
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)

special_print()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


### Q7

Write a function, `calculateSum(l,k)` which will take a list, `l` and a number `k` as input and return two numbers from `l` that add up to `k`.

In [17]:
l = [1, 21, 3, 14, 5, 60, 7, 6]
k = 81

def calculateSum(l,k):
    seen_numbers = set()
    for num in l:
        complement = k - num
        if complement in seen_numbers:
            return num, complement
        seen_numbers.add(num)
    return None # Return None if no such pair is found

print(calculateSum(l,k))

(60, 21)


### Q8

Write a function, `find_students`  that receives the `students` dictionary and an `address`, and returns a `list` with names in sorted order of all students whose address matches the address in the argument.

In [18]:
def find_students(address, students):
  matching_students = []
  for name, details in students.items():
    if details["address"] == address:
      matching_students.append(name)
  return sorted(matching_students)

students = {
      "Ali": {"age": 6, "address": "Lahore"},
      "Ahmad": {"age": 15, "address": "Islamabad"},
      "Eesha": {"age": 21, "address": "Karachi"},
      "Bilal": {"age": 10, "address": "Lahore"}
}
print(find_students("Lahore", students))

['Ali', 'Bilal']


### Q9

Given an unsorted list of integers, write a function first_missing_positive that returns the smallest missing positive integer.

In [19]:
def first_missing_positive(nums):
    num_set = set()
    for num in nums:
        if num > 0:
            num_set.add(num)

    i = 1
    while True:
        if i not in num_set:
            return i
        i += 1

print(first_missing_positive([3, 4, -1, 1]))  # Output: 2
print(first_missing_positive([1, 2, 0]))      # Output: 3
print(first_missing_positive([7, 8, 9, 11]))  # Output: 1

2
3
1


### Q10

Write a function flatten_dict that takes a nested dictionary and returns a flattened version where keys are concatenated with underscores for nested levels. Handle edge cases like empty dictionaries or non-dictionary values.

In [ ]:
nested_dict = {
    'a': 1,
    'b': {
        'c': 2,
        'd': {
            'e': 3,
            'f': 4
        }
    },
    'g': 5
}

def flatten_dict(d, parent_key='', sep='_'):
    flattened_items = {}
    if not isinstance(d, dict): # Handle non-dictionary values if called recursively with a non-dict
        return {parent_key: d}

    for key, value in d.items():
      new_key = parent_key + sep + str(key) if parent_key else str(key)
      if isinstance(value, dict):
        flattened_items.update(flatten_dict(value, new_key, sep=sep))
      else:
        flattened_items[new_key] = value

        return flattened_items

print(flatten_dict(nested_dict))
# Expected Output: {'a': 1, 'b_c': 2, 'b_d_e': 3, 'b_d_f': 4, 'g': 5}

### Q11

Given a list of tuples representing student names and their scores, write a function top_student that returns the name of the student with the highest score.

In [26]:
scores = [("Ali", 85), ("Ahmad", 92), ("Aisha", 78)]

def top_student(students):
    if not students:
        return None

    max_score = -1
    top_name = ""

    for name, score in students:
        if score > max_score:
            max_score = score
            top_name = name

    return top_name

print(top_student(scores))  # Expected output: "Ahmad"

Ahmad


### Q12
Write a function count_vowels that takes a string and returns a dictionary where the keys are vowels (a, e, i, o, u) and the values are their respective counts in the string (case-insensitive).

In [27]:
text = "Hello, how are you today?"

def count_vowels(s):
    vowels = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
    s_lower = s.lower()
    for char in s_lower:
        if char in vowels:
            vowels[char] += 1
    return vowels

print(count_vowels(text))  # Expected output: {'a': 2, 'e': 2, 'i': 0, 'o': 3, 'u': 1}

{'a': 2, 'e': 2, 'i': 0, 'o': 4, 'u': 1}


### Q13

Given a list of numbers, write a function remove_outliers that removes the smallest and largest numbers from the list and returns the modified list.

In [28]:
numbers = [12, 3, 45, 7, 1, 67, 9]

def remove_outliers(lst):
    if len(lst) < 2:
        return [] # Or raise an error, depending on desired behavior for small lists
    sorted_lst = sorted(lst)
    return sorted_lst[1:-1]

print(remove_outliers(numbers))  # Expected output: [12, 3, 45, 7, 9]

[3, 7, 9, 12, 45]


### Q14
Longest Consecutive Sequence in a List
Given an unsorted list of integers, write a function longest_consecutive_sequence that returns the length of the longest consecutive sequence of numbers (e.g., [100, 4, 200, 1, 3, 2] → 4 because 1, 2, 3, 4 is the longest sequence).

In [29]:
nums = [100, 4, 200, 1, 3, 2, 101, 99, 102, 103, 104]

def longest_consecutive_sequence(nums):
    if not nums:
        return 0

    num_set = set(nums)
    max_length = 0

    for num in nums:
        # Check if the current number is the start of a sequence
        if (num - 1) not in num_set:
            current_num = num
            current_length = 1

            # Count the length of the consecutive sequence
            while (current_num + 1) in num_set:
                current_num += 1
                current_length += 1

            max_length = max(max_length, current_length)

    return max_length

print(longest_consecutive_sequence(nums))

6


### Q15
Implement a Trie (Prefix Tree)
Write a class Trie with methods insert(word), search(word), and startsWith(prefix) to efficiently store and retrieve words.

In [30]:
class Trie:
    def __init__(self):
        self.root = {}

    def insert(self, word):
        node = self.root
        for char in word:
            node = node.setdefault(char, {})
        node['_end_'] = True

    def search(self, word):
        node = self.root
        for char in word:
            if char not in node:
                return False
            node = node[char]
        return '_end_' in node

    def startsWith(self, prefix):
        node = self.root
        for char in prefix:
            if char not in node:
                return False
            node = node[char]
        return True

trie = Trie()
trie.insert("apple")
print(trie.search("apple"))   # True
print(trie.search("app"))     # False
print(trie.startsWith("app")) # True
trie.insert("app")
print(trie.search("app"))     # True

True
False
True
True


### Q16
Design a CircularBuffer class that supports:

append(x): Add an element to the buffer. If full, overwrite the oldest element.

get(): Return the buffer as a list in insertion order.



In [31]:
class CircularBuffer:
    def __init__(self, size):
        self.size = size
        self.buffer = [None] * size  # Initialize with fixed size
        self.head = 0  # Pointer to the next write position (and effectively the oldest element when full)
        self.count = 0 # Number of elements currently in the buffer

    def append(self, x):
        self.buffer[self.head] = x
        self.head = (self.head + 1) % self.size
        if self.count < self.size:
            self.count += 1

    def get(self):
        if self.count < self.size:
            return self.buffer[:self.count]
        else:
            # If full, the logical start is at 'head', so rotate the list
            return self.buffer[self.head:] + self.buffer[:self.head]


cb = CircularBuffer(3)
cb.append(1)
cb.append(2)
cb.append(3)
print(cb.get())  # [1, 2, 3]
cb.append(4)
print(cb.get())  # [2, 3, 4]

[1, 2, 3]
[2, 3, 4]


### Q17
Write a function one_hot_encode that converts categorical labels (e.g., ["cat", "dog", "bird"]) into one-hot encoded arrays without using OneHotEncoder.

In [32]:
import numpy as np

def one_hot_encode(labels):
    """
    labels: List of categorical labels (e.g., ["cat", "dog", "cat"]).
    Returns a 2D NumPy array where each row is a one-hot vector.
    """
    if not labels:
        return np.array([])

    # Get unique labels and create a mapping from label to index
    unique_labels = sorted(list(set(labels)))
    label_to_index = {label: i for i, label in enumerate(unique_labels)}

    num_labels = len(unique_labels)
    num_samples = len(labels)

    # Initialize an empty NumPy array with zeros
    one_hot_matrix = np.zeros((num_samples, num_labels))

    # Populate the one-hot matrix
    for i, label in enumerate(labels):
        index = label_to_index[label]
        one_hot_matrix[i, index] = 1

    return one_hot_matrix

labels = ["cat", "dog", "bird", "cat"]
print(one_hot_encode(labels))
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [1. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
